config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "entrance#index"
  resources :users
  resources :stocks
  resources :articles do
    resources :comments, shallow: true
  end
  resources :likes
  get 'soon', to: 'stocks#soon'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get "/oauth/callback", to: "oauths#callback"
  get "/oauth/:provider", to: "oauths#oauth", as: :login_line

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
 
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    accepts_nested_attributes_for :article_categories
    has_many :categories, through: :article_categories
    validates :keyword, presence: true, length: {maximum: 18}
    validates :body, length: {maximum: 120}, presence: true

    mount_uploader :photo, PhotoUploader
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: %i[index show]
    
    def index
        @categories = Category.all
        @q = Article.ransack(params[:q])
        @articles = @q.result(distinct: true).all.order(created_at: :desc)
        @phone_articles = Article.all.order(created_at: :desc).limit(3)
    end

    def new
        @article = Article.new
        @article.article_categories.build
    end

    def show
        @article = Article.find(params[:id])
        @comment = Comment.new
        @comments = @article.comments.includes(:user).order(created_at: :desc)

        set_meta_tags({
            title: 'お気に入りが見つかる日用品管理アプリ',
            description: @article.body || @article.body.truncate(50),
            og: {
              title: 'お気に入りが見つかる日用品管理アプリ',
              description: @article.body || @article.body.truncate(50),
              image: @article.photo.present? ? @article.photo_url(:art_img) : view_context.image_url('app_face.png'),
              url: "https://www.stockandpost.com"
            }
        })
    end

    def create
        @article = Article.new(article_params)
        @article.user_id = current_user.id
        
        if @article.save
            redirect_to articles_path
        else
            respond_to do |format|
                format.turbo_stream do
                    render turbo_stream: turbo_stream.update('flash') {
                    render_to_string inline: "<div id='flash' class='text-danger text-center'>入力内容に不備があります</div>"
                    }
                end
            end
        end
    end

    def edit
        @article = current_user.articles.find(params[:id])
    end

    def update
        @article = current_user.articles.find(params[:id])
        ActiveRecord::Base.transaction do
            @article.article_categories.destroy_all
            if @article.update(article_params)
                #ストック数が減少したら、quantity_update_atを変更する仕様にしているため、ここで在庫減少日を更新する必要はない。
                redirect_to articles_path
            else
                respond_to do |format|
                    format.turbo_stream do
                        render turbo_stream: turbo_stream.update('flash') {
                        render_to_string inline: "<div id='flash' class='text-danger text-center'>入力内容に不備があります</div>"
                        }
                    end
                end
            end
        end
    end

    def destroy
        @article = current_user.articles.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

    private

    def article_params
        params.require(:article).permit(:keyword,:body, :photo, :photo_cache, article_categories_attributes: [:category_id])
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_like_button.html.erb
<%= turbo_frame_tag dom_id(article, :like_button), class: "mt-2" do %>
    <% if logged_in? %>
        <% if current_user.like_arts.include?(article) %>
            <%= link_to like_path(id: article.id), class: "mt-3", data: { turbo_method: :delete } do %>
                <i class="bi bi-hand-thumbs-up-fill mt-3 already_good"></i>
            <% end %>
        <% else %>
            <%= link_to likes_path(id: article.id), class: "mt-3", data: { turbo_method: :post } do %>
                <i class="bi bi-hand-thumbs-up mt-3 good_button"></i>
            <% end %>
        <% end %>
    <% else %>
        <i class="bi bi-hand-thumbs-up good_icon mt-3"></i>
    <% end %>
    <span class="mt-4">いいね:<%= article.likes.count %></span>
<% end %>

app/views/articles/edit.html.erb
<%= content_for(:title,'投稿記事作成ページ') %>
<div class="form_container bg-white text-dark">
  <div class="form_box mx-3 my-3">
    <h3 class="mx-3 mt-4">投稿記事の編集</h3>
    <div class="form">
      <div id="flash"></div>
      <% if @article.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
            <ul>
                <% @article.errors.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
      <% end %>
      <%= form_with model: @article do |f| %>
        <%= f.fields_for :article_categories do |article_category| %>
          <div class="category_form">
            <%= article_category.label :カテゴリー, class: "category_label" %>
            <%= article_category.collection_select :category_id, Category.all, :id, :name,{}, { class: "category_name_input" } %>
          </div> 
        <% end %>
        
        <div class="d-flex my-3 mr-5">
          <%= f.label :キーワード, class: "label text-center" %>
          <%= f.text_field :keyword, class: "form-control mr-5", placeholder: "洗剤　部屋干し"  %>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :本文, class: "label text-center" %>
          <%= f.text_area :body, class: "form-control article_body_form mr-5", placeholder: "120文字まで入力できます", rows: 8 %>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :画像, class: "label text-center"  %>
          <%= f.file_field :photo, class: "form-control mr-5", accept: 'image/*' %>
          <%= f.hidden_field :photo_cache %>
        </div>

        <div class="photo_now mb-3">
          <%= image_tag @article.photo_url, class: 'photo mr-5' %>
        </div>



        <%= f.submit "変更内容を保存する", class: "submit_button"%>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container d-flex mt-5">
    <div>
        <%= render "shared/index_button" %>
        <div class="index_container bg-white text-dark">
            <div class="d-flex">
                <% if logged_in? %>
                    <div>
                        <%= link_to new_article_path, class: "insert_button" do%>
                                <div class="btn btn-info mt-2 ml-3">投稿する</div>
                        <% end %>
                    </div>
                <% else %>
                    <div>
                        <%= link_to login_path, class: "insert_button" do%>
                                <div class="btn btn-info mt-2 ml-3">ログインして投稿する</div>
                        <% end %>
                    </div>
                <% end %>
                <div class="search">
                    <p class ="pt-1 pr-2">カテゴリー検索</p>
                    <%= search_form_for @q, url: articles_path, html: { class: "d-flex" } do |f| %>
                     <%= f.collection_select :categories_name_cont, @categories, :name, :name, { include_blank: "全てのカテゴリー" }, { class: 'form-control mr-2' } %>
                     <%= f.submit '検索', class: 'btn btn-primary ml-1' %>
                    <% end %>
                </div>
            </div>
            <div class="article_container">
                <% if @articles.present? %>
                    <% @articles.each do |article| %>
                        <div class="article">
                            <div class="left_contents">
                                <h5>投稿ユーザー名：　<%= article.user.name %></h5>
                                <div class="article_header">
                                    <p class="mt-1">カテゴリー：　<%= article.categories.first.name %></p>
                                    <p>キーワード：　<%= article.keyword %></p>
                                </div>
                                
                                <p class="mt-3 ml-3"><%= safe_join(article.body.split("\n"),tag(:br)) %></p>
                                <%= link_to "この投稿の詳細ページへ", article_path(article)  %>
                            </div>
                            <div class="right_contents">
                                <p>投稿日:　<%= article.created_at.strftime('%Y/%m/%d')  %></p>
                                <div class="img">
                                    <%= image_tag article.photo_url(:art_img) %>
                                </div>
                                <div class="d-flex">
                                    <%= render partial: "articles/like_button", locals: { article: article } %>
                                    <% if current_user && article.user_id == current_user.id %>
                                        <div class="d-flex mt-3 ml-3">
                                            <%= link_to edit_article_path(article.id), class: "insert_button" do%>
                                                <div class="btn btn-info">編集する</div>
                                            <% end %>
                                            <%= link_to article_path(article.id), class: "insert_button", data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete} do%>
                                                <div class="btn btn-danger  ml-3">削除する</div>
                                            <% end %>                            
                                        </div>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <div class ="mt-5 text-center">投稿された記事がありません</div>
                <% end %>
           </div>
        </div>
    </div>
    <div>
        <%= render "shared/topics" %>
    </div>
</div>

app/views/articles/new.html.erb
<%= content_for(:title,'投稿記事作成ページ') %>
<div class="form_container bg-white text-dark">
  <div class="form_box mx-3 my-3">
    <h3 class="mx-3 mt-4">投稿記事の作成</h3>
    <div class="form">
      <div id="flash"></div>
      <%= form_with model: @article do |f| %>
        <%= f.fields_for :article_categories do |article_category| %>
          <div class="category_form">
            <%= article_category.label :カテゴリー, class: "category_label" %>
            <%= article_category.collection_select :category_id, Category.all, :id, :name,{}, { class: "category_name_input" } %>
          </div> 
        <% end %>
        
        <div class="d-flex my-3 mr-5">
          <%= f.label :キーワード, class: "label text-center" %>
          <%= f.text_field :keyword, class: "form-control mr-5", placeholder: "洗剤　部屋干し（必須）"  %>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :本文, class: "label text-center" %>
          <%= f.text_area :body, class: "form-control article_body_form mr-5", placeholder: "120文字まで入力できます（必須）", rows: 8 %>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :画像, class: "label text-center"  %>
          <%= f.file_field :photo, class: "form-control mr-5", accept: 'image/*' %>
          <%= f.hidden_field :photo_cache %>
        </div>

        <%= f.submit "保存して投稿する", class: "submit_button"%>
      <% end %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<%= content_for(:title,'記事詳細ページ') %>
<div class="article_show_container bg-white text-dark">
    <div class="article mt-2">
        <div class="left_contents">
            <h5>投稿ユーザー名：　<%= @article.user.name %></h5>
            <div class="article_header">
                <p class="mt-1">カテゴリー：　<%= @article.categories.first.name %></p>
                <p>キーワード：　<%= @article.keyword %></p>
            </div>
            
            <p class="mt-3 ml-3"><%= safe_join(@article.body.split("\n"),tag(:br)) %></p>
        </div>
        <div class="right_contents">
            <p>投稿日:　<%= @article.created_at.strftime('%Y/%m/%d')  %></p>
            <div class="img">
                <%= image_tag @article.photo_url(:art_img)%>
            </div>
            <div class="d-flex">
                <%= render partial: "articles/like_button", locals: { article: @article } %>
                <% if current_user && current_user.id == @article.user_id %>
                    <div class="d-flex mt-3 ml-2">
                        <%= link_to edit_article_path(@article.id), class: "insert_button" do%>
                            <div class="btn btn-info ">編集する</div>
                        <% end %>
                        <%= link_to article_path(@article.id), class: "insert_button", data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete} do%>
                            <div class="btn btn-danger  ml-3">削除する</div>
                        <% end %>                            
                    </div>
                <% end %>
            </div>

        </div>
    </div>
    <h5 class="comment_title">comments</h5>
    <div class="comments_container">
        <% if current_user %>
            <div class="comment">
                <%= form_with model: @comment, url: article_comments_path(@article) do |f| %>
                    <div class="d-flex comment_area">
                        <%= f.text_area :body, class: "form-control", placeholder: 'コメントを入力してください' %>
                        <%= f.submit "コメントする", class: "comment_submit_button"%>
                    </div>
                <% end %>
            </div>
        <% end %>
        <% if @comments.present? %>
            <% @comments.each do |comment| %>
                <div class="comment">
                    <%= safe_join(comment.body.split("\n"),tag(:br)) %>
                </div>
                <% if current_user && current_user.own?(comment) %>
                    <div class="comment_button mt-1">
                        <%= link_to comment_path(comment.id), class: "insert_button", data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete} do%>
                            <div class="comment_destroy_button  ml-3">削除する</div>
                        <% end %>                            
                    </div>
                <% end %>
            <% end %>
        <% else %>
            <div class="text-center">まだコメントがありません</div>
        <% end %>
    </div>
</div>