config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "entrance#index"
  resources :users
  resources :stocks
  resources :articles do
    resources :comments, shallow: true
  end
  resources :likes
  get 'soon', to: 'stocks#soon'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get "/oauth/callback", to: "oauths#callback"
  get "/oauth/:provider", to: "oauths#oauth", as: :login_line

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
 
end

app/controllers/entrance_controller.rb
class EntranceController < ApplicationController

    def index
    end

end

app/helpers/entrance_helper.rb
module EntranceHelper
end

app/views/entrance/index.html.erb
<body>
  <div class="container pt-5 pb-5 d-flex justify-content-center">
    <div class="top_page_box mt-5 col-6 text-center">
      <h3 class="mt-3 font-weight-bold">お気に入りが見つかる<br>日用品管理アプリ</h3>
      <p class= "mt-5">このアプリは日用品のストックを管理するだけでなく、<br>
        お気に入りの商品や様々な情報を発信したり、<br>
        チェックすることができます。<br>
        他のユーザーの投稿をチェックしながら<br>
        身の回りの日用品を充実させていきましょう！
      </p>
    </div>
  </div>
  <div class= "d-flex justify-content-center pt-5 my-5 py-5">
    <% if logged_in? %>
      <%= link_to articles_path, class: "btn btn-default" do%>
        <div class="rooting_button px-5 py-4 mr-2">投稿を見る</div>
      <% end %>
      <%= link_to stocks_path, class: "btn btn-default" do%>
        <div class="rooting_button px-4 py-4 ml-3">在庫を確認する</div>
      <% end %>
    <% else %>
      <%= link_to articles_path, class: "btn btn-default" do%>
        <div class="rooting_button p-3 mr-2">投稿を見てみる<br>（ログイン不要）</div>
      <% end %>
      <%= link_to login_path, class: "btn btn-default" do%>
        <div class="rooting_button p-4 mx-5">ログイン</div>
      <% end %>
      <%= link_to new_user_path, class: "btn btn-default" do%>
        <div class="rooting_button p-4 ml-2">新規ユーザー登録</div>
      <% end %>      
    <% end %>
  </div>

</body>