config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "entrance#index"
  resources :users
  resources :stocks
  resources :articles do
    resources :comments, shallow: true
  end
  resources :likes
  get 'soon', to: 'stocks#soon'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get "/oauth/callback", to: "oauths#callback"
  get "/oauth/:provider", to: "oauths#oauth", as: :login_line

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
 
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    has_many :stock_categories, dependent: :destroy
    has_many :categories, through: :stock_categories
    accepts_nested_attributes_for :stock_categories
    validates :name, presence: true, length: {maximum: 25}
    validates :purchase_interval, allow_blank: true, numericality: {only_integer: true}
    validates :memo, length: {maximum: 120}
    validates :stock_quantity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

    def line_push
        client ||= Line::Bot::V2::MessagingApi::ApiClient.new(
            channel_access_token: ENV.fetch("LINE_CHANNEL_TOKEN_MESSAGE")
        )

        request = Line::Bot::V2::MessagingApi::PushMessageRequest.new(
            to: self.user.email,
            messages: [
                Line::Bot::V2::MessagingApi::TextMessage.new(text: "#{self.user.name}さま　\n残り１つとなった在庫をお知らせします!\n\n#{self.name}")
            ]
        )
        
        response = client.push_message(push_message_request: request)
        puts response
    end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
    before_action :require_login
    def index
        @categories = Category.all
        @q = Stock.ransack(params[:q])
        @stocks = @q.result(distinct: true).where(user_id: current_user.id)
        @phone_articles = Article.all.order(created_at: :desc).limit(3)
    end

    def new
        @stock = Stock.new
        @stock.stock_categories.build
    end

    def create
        @stock = Stock.new(stock_params)
        @stock.user_id = current_user.id
        @stock.quantity_update_at = Time.current
        
        if @stock.save
            redirect_to stocks_path
        else
            respond_to do |format|
                format.turbo_stream do
                    render turbo_stream: turbo_stream.update('flash') {
                    render_to_string inline: "<div id='flash' class='text-danger text-center'>入力内容に不備があります</div>"
                    }
                end
            end
        end
    end

    def show
        @stock = current_user.stocks.includes(:categories).find(params[:id])
        @category = @stock.categories.first.name
    end

    def edit
        @stock = current_user.stocks.find(params[:id])
    end

    def update
        @stock = current_user.stocks.find(params[:id])

        ActiveRecord::Base.transaction do
            @stock.stock_categories.destroy_all
            if @stock.update(stock_params)
                #ストック数が減少したら、quantity_update_atを変更する仕様にしているため、ここで在庫減少日を更新する必要はない。
                redirect_to stocks_path
            else
                respond_to do |format|
                    format.turbo_stream do
                        render turbo_stream: turbo_stream.update('flash') {
                        render_to_string inline: "<div id='flash' class='text-danger text-center'>入力内容に不備があります</div>"
                        }
                    end
                end
            end
        end
    end

    def destroy
        @stock = current_user.stocks.find(params[:id])
        @stock.destroy!
        redirect_to stocks_path, success: "削除しました！", status: :see_other
    end

    def soon
        @categories = Category.all
        @q = Stock.ransack(params[:q])
        @stocks = @q.result(distinct: true).where(user_id: current_user.id).where("stock_quantity <= ?" , 1)
        @phone_articles = Article.all.order(created_at: :desc).limit(3)
    end

    private

    def stock_params
        params.require(:stock).permit(:name,:purchase_interval,:stock_quantity,:memo, stock_categories_attributes: [:category_id]).tap do |whitelisted|
            whitelisted[:purchase_interval] = params[:stock][:purchase_interval].tr('０-９', '0-9') if params[:stock][:purchase_interval]
            whitelisted[:stock_quantity] = params[:stock][:stock_quantity].tr('０-９', '0-9') if params[:stock][:stock_quantity]
        end
    end

    def not_authenticated
        redirect_to login_path
    end

end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/stocks/edit.html.erb
<%= content_for(:title,'ストック編集ページ') %>
<div class="form_container bg-white text-dark">
  <div class="form_box mx-3 my-3">
    <h3 class="mx-3 mt-4">ストック編集</h3>
    <div class="form">
      <div id="flash"></div>
      <%= form_with model: @stock do |f| %>
        <div class="d-flex mb-3 mr-5">
          <%= f.label :ストック名, class: "label text-center" %>
          <%= f.text_field :name, class: "form-control mr-5 text-center" %>
        </div>  

        <%= f.fields_for :stock_categories do |stock_category| %>
          <div class="category_form">
            <%= stock_category.label :カテゴリー, class: "category_label" %>
            <%= stock_category.collection_select :category_id, Category.all, :id, :name,{}, { class: "category_name_input" } %>
          </div> 
        <% end %>
        
        <div class="d-flex my-3 mr-5">
          <%= f.label :購入頻度, class: "label text-center" %>
          <%= f.number_field :purchase_interval, class: "form-control purchase_interval text-right", min: "1" %>
          <span class="mr-5 mt-1">日毎に購入</span>
        </div>  
        <div>
            <p class="lh-1 mr-5 mb-5">※普段の購入頻度（設定された頻度で在庫が自動で減少します）<br>※ストックが無くなっても通知する必要がない場合は空欄でOKです</p>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :ストック数, class: "label text-center mr-4" %>
          <%= f.number_field :stock_quantity, class: "form-control purchase_interval text-right", min: "1" %>
          <span class="mr-5 mt-1">（個/袋/枚/本）</span>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :メモ, class: "label text-center" %>
          <%= f.text_area :memo, class: "form-control mr-5" %>
        </div>

        <%= f.submit "保存する", class: "submit_button"%>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/index.html.erb
<div class="container d-flex mt-5">
    <div>
        <%= render "shared/index_button" %>
        <div class="index_container bg-white text-dark">
            <div id = "test" class="text-center text-danger py-1">残りの数は設定した購入頻度によって自動的に減少します！</div>
            <div class="index_box mx-3 mb-3">
                <div class="search">
                    <p class ="pt-1 pr-2">カテゴリー検索</p>
                    <%= search_form_for @q, url: stocks_path, html: { class: "d-flex" } do |f| %>
                     <%= f.collection_select :categories_name_cont, @categories, :name, :name, { include_blank: "全てのカテゴリー" }, { class: 'form-control mr-2' } %>
                     <%= f.submit '検索', class: 'btn btn-primary ml-1' %>
                    <% end %>
                </div>
                <div class="d-inline-block"><p class="ml-5 mt-3">ストック名（在庫数自動更新日）　　　　　　　　　　　　残っている数</p></div>
                <div class="d-inline-block ml-4">
                    <%= link_to new_stock_path, class: "insert_button" do%>
                        <div class="btn btn-info">ストックを追加</div>
                    <% end %>
                </div>
                <% if @stocks.present? %>  
                    <% @stocks.each do |stock| %>
                        <div class="stocks">
                            <%= link_to stock_path(stock.id), class: "stock_card" do %>
                                <div class="stock_index ml-5 ">
                                    <div class="stock_name d-inline ml-3">
                                        <%= stock.name %>
                                        <span>（<%= stock.quantity_update_at.strftime('%Y/%m/%d')  %>）</span>
                                    </div>
                                    <div class="stock_amount d-inline">
                                        <%= stock.stock_quantity %>
                                    </div>
                                </div>
                            <% end %>
                            <div>
                                <%= link_to edit_stock_path(stock), class: "edit_button" do%>
                                    <div class="edit_button text-body">編集</div>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <div class="mt-5 text-center">登録されたストックがありません</div>
                <% end %>
            </div>
        </div>
    </div>
    <%= render "shared/topics" %>
</div>

app/views/stocks/new.html.erb
<%= content_for(:title,'ストック登録ページ') %>
<div class="form_container bg-white text-dark">
  <div class="form_box mx-3 my-3">
    <h3 class="mx-3 mt-4">ストック登録</h3>
    <div class="form">
      <div id="flash"></div>
      <%= form_with model: @stock do |f| %>
        <div class="d-flex mb-3 mr-5">
          <%= f.label :ストック名, class: "label text-center" %>
          <%= f.text_field :name, class: "form-control mr-5 text-center", placeholder:"（必須）" %>
        </div>  

        <%= f.fields_for :stock_categories do |stock_category| %>
          <div class="category_form">
            <%= stock_category.label :カテゴリー, class: "category_label" %>
            <%= stock_category.collection_select :category_id, Category.all, :id, :name,{}, { class: "category_name_input" } %>
          </div> 
        <% end %>
        
        <div class="d-flex my-3 mr-5">
          <%= f.label :購入頻度, class: "label text-center" %>
          <%= f.number_field :purchase_interval, class: "form-control purchase_interval text-right", min: "1"%>
          <span class="mr-5 mt-1">日毎に購入</span>
        </div>  
        <div>
            <p class="lh-1 mr-5 mb-5">※普段の購入頻度（設定された頻度で在庫が自動で減少します）<br>※ストックが無くなっても通知する必要がない場合は空欄でOKです</p>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :ストック数, class: "label text-center mr-4" %>
          <%= f.number_field :stock_quantity, class: "form-control purchase_interval text-right", placeholder:"（必須）",min: "1" %>
          <span class="mr-5 mt-1">（個/袋/枚/本）</span>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :メモ, class: "label text-center" %>
          <%= f.text_area :memo, class: "form-control mr-5" %>
        </div>

        <%= f.submit "登録する", class: "submit_button"%>
      <% end %>
    </div>
  </div>
</div>

app/views/stocks/show.html.erb
<%= content_for(:title,'ストック情報ページ') %>
<div class="form_container bg-white text-dark">
  <div class="form_box mx-3 my-3">
    <h3 class="mx-3 mt-4 d-inline-block">ストック情報</h3>
    <div class="form">
      <%= form_with model: @stock do |f| %>
        <div class="d-flex mb-3 mr-5">
          <%= f.label :ストック名, class: "label text-center" %>
          <%= f.text_field :name, readonly: true, class: "form-control mr-5 text-center" %>
        </div> 

        <div class="category_form mb-3 mr-5">
          <div class="category_label">カテゴリー</div>
          <div class="category_name">
            <%= @category %>
          </div>
        </div> 
        
        <div class="d-flex mb-3 mr-5">
          <%= f.label :購入頻度, class: "label text-center" %>
          <%= f.text_field :purchase_interval, readonly: true, class: "form-control purchase_interval text-right" %>
          <span class="mr-5 mt-1">日毎に購入</span>
        </div>  
        <div>
            <p class="lh-1 mr-5 mb-5">※普段の購入頻度（設定された頻度で在庫が自動で減少します）<br>※ストックが無くなっても通知する必要がない場合は空欄でOKです</p>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :ストック数, class: "label text-center mr-4" %>
          <%= f.text_field :stock_quantity, readonly: true, class: "form-control purchase_interval text-right" %>
          <span class="mr-5 mt-1">（個/袋/枚/本）</span>
        </div>

        <div class="d-flex mb-3 mr-5">
          <%= f.label :メモ, class: "label text-center" %>
          <%= f.text_area :memo, readonly: true, class: "form-control mr-5" %>
        </div>
      <% end %>
      <div>
        <%= link_to stock_path(@stock), class: "submit_button d-inline-block", data: { turbo_confirm: "本当に削除しますか？", turbo_method: :delete} do%>
            <div class="text-body">削除する</div>
        <% end %>
        <%= link_to edit_stock_path(@stock), class: "submit_button d-inline-block" do%>
            <div class="text-body">編集する</div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/stocks/soon.html.erb
<div class="container d-flex mt-5">
    <div>
        <%= render "shared/index_button" %>
        <div class="index_container bg-white text-dark">
            <div class="text-center text-danger py-1">残りが１つ以下のストックを表示しています！</div>
            <div class="index_box mx-3 mb-3">
                <div class="search">
                    <p class ="pt-1 pr-2">カテゴリー検索</p>
                    <%= search_form_for @q, url: soon_path, html: { class: "d-flex" } do |f| %>
                     <%= f.collection_select :categories_name_cont, @categories, :name, :name, { include_blank: "全てのカテゴリー" }, { class: 'form-control mr-2' } %>
                     <%= f.submit '検索', class: 'btn btn-primary ml-1' %>
                    <% end %>
                </div>
                <div class="d-inline-block"><p class="ml-5 mt-3">ストック名（在庫数自動更新日）　　　　　　　　　　　　残っている数</p></div>
                <div class="d-inline-block ml-4">
                    <%= link_to new_stock_path, class: "insert_button" do%>
                        <div class="btn btn-info">ストックを追加</div>
                    <% end %>
                </div>
                <% if @stocks.present? %>  
                    <% @stocks.each do |stock| %>
                        <div class="stocks">
                            <%= link_to stock_path(stock.id), class: "stock_card" do %>
                                <div class="stock_index ml-5 ">
                                    <div class="stock_name d-inline ml-3">
                                        <%= stock.name %>
                                        <span>（<%= stock.quantity_update_at.strftime('%Y/%m/%d')  %>）</span>
                                    </div>
                                    <div class="stock_amount d-inline">
                                        <%= stock.stock_quantity %>
                                    </div>
                                </div>
                            <% end %>
                            <div>
                                <%= link_to edit_stock_path(stock.id), class: "edit_button" do%>
                                    <div class="edit_button text-body">編集</div>
                                <% end %>
                            </div>
                        </div>
                    <% end %>
                <% else %>
                    <div class="mt-5 text-center">ストックが１つ以下に該当するものはありません。</div>
                <% end %>
            </div>
        </div>
    </div>
    <%= render "shared/topics" %>
</div>