config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "entrance#index"
  resources :users
  resources :stocks
  resources :articles do
    resources :comments, shallow: true
  end
  resources :likes
  get 'soon', to: 'stocks#soon'
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get "/oauth/callback", to: "oauths#callback"
  get "/oauth/:provider", to: "oauths#oauth", as: :login_line

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    # 全ての列を検索可能にする
    authorizable_ransackable_attributes
  end
  def self.ransackable_associations(auth_object = nil)
    # 全ての関連テーブルを検索可能にする
    authorizable_ransackable_associations
  end
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories, dependent: :destroy
    has_many :comments, dependent: :destroy
    has_many :likes, dependent: :destroy
    accepts_nested_attributes_for :article_categories
    has_many :categories, through: :article_categories
    validates :keyword, presence: true, length: {maximum: 18}
    validates :body, length: {maximum: 120}, presence: true

    mount_uploader :photo, PhotoUploader
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
    belongs_to :article
    belongs_to :category
end

app/models/authentication.rb
class Authentication < ApplicationRecord
    belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :article_categories
    has_many :stock_categories
    has_many :articles, through: :article_categories
    has_many :stocks, through: :stock_categories
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :article
    validates :body, length: {maximum: 50}
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :article

    validates :user_id, uniqueness: { scope: :article_id }
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :user
    has_many :stock_categories, dependent: :destroy
    has_many :categories, through: :stock_categories
    accepts_nested_attributes_for :stock_categories
    validates :name, presence: true, length: {maximum: 25}
    validates :purchase_interval, allow_blank: true, numericality: {only_integer: true}
    validates :memo, length: {maximum: 120}
    validates :stock_quantity, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}

    def line_push
        client ||= Line::Bot::V2::MessagingApi::ApiClient.new(
            channel_access_token: ENV.fetch("LINE_CHANNEL_TOKEN_MESSAGE")
        )

        request = Line::Bot::V2::MessagingApi::PushMessageRequest.new(
            to: self.user.email,
            messages: [
                Line::Bot::V2::MessagingApi::TextMessage.new(text: "#{self.user.name}さま　\n残り１つとなった在庫をお知らせします!\n\n#{self.name}")
            ]
        )
        
        response = client.push_message(push_message_request: request)
        puts response
    end
end

app/models/stock_category.rb
class StockCategory < ApplicationRecord
    belongs_to :stock
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications
  
  has_many :stocks, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :like_arts, through: :likes, source: :article
  validates :password, length: {minimum: 3}, if: -> {new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> {new_record? || changes[:crypted_password] }
  validates :password_confirmation,presence: true, if: -> {new_record? || changes[:crypted_password] }
  validates :name, presence: true, length: { maximum: 10 }
  validates :email, presence: true, uniqueness: true

  def own?(object)
    id == object&.user_id
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @article = Article.find(params[:id])
        current_user.like_arts << @article
        respond_to do |format|
            format.turbo_stream
            format.html { redirect_to params[:redirect_to] || articles_path }
        end
    end

    def destroy
        @article = Article.find(params[:id])
        current_user.like_arts.destroy(@article)
        redirect_to params[:redirect_to] || articles_path
        respond_to do |format|
            format.turbo_stream
            format.html { redirect_to params[:redirect_to] || articles_path }
        end
    end

end

app/controllers/oauths_controller.rb
class OauthsController < ApplicationController
    def oauth
      login_at(params[:provider])
    end
  
    def callback
      provider = auth_params[:provider]

      if (@user = login_from(provider))
        redirect_to stocks_path, allow_other_host: true
      else
        begin
            @user = create_from(provider)
            auto_login(@user)
            redirect_to stocks_path #新規登録&ログインして飛ぶとこ
        rescue StandardError
          redirect_to root_path, allow_other_host: true
        end
      end
    end 

    private

    def auth_params
        params.permit(:code, :provider, :error, :state)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :require_login
    skip_before_action :require_login, only: %i[new create]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            auto_login(@user)
            redirect_to root_path
        else
            respond_to do |format|
                format.turbo_stream do
                    render turbo_stream: turbo_stream.update('flash') {
                    render_to_string inline: "<div id='flash' class='text-danger text-center'>入力内容に不備があります</div>"
                    }
                end
            end
        end
    end

    private

    def not_authenticated
        redirect_to login_path
    end

    def user_params
        params.require(:user).permit(:name,:password,:email,:password_confirmation)
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
    def page_title(title = '')
        app_title = 'お気に入りが見つかる日用品管理アプリ'
        title.present? ? "#{title}" : app_title
    end

    def default_meta_tags
        {
          site: 'お気に入りが見つかる日用品管理アプリ',
          title: 'お気に入りが見つかる日用品管理アプリ',
          reverse: true,
          charset: 'utf-8',
          description:'日用品を自動で管理しつつ、お気に入りの商品も共有できるwebアプリです。',
          keywords: '日用品、管理、投稿',
          canonical: "https://www.stockandpost.com",
          separator: '|',
          og:{
            site_name: :site,
            title: :title,
            description: :description,
            type: 'website',
            url: "https://www.stockandpost.com",
            image: image_url('app_face.png'),
            local: 'ja-JP'
          }
        }
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/entrance_helper.rb
module EntranceHelper
end

app/helpers/oauths_helper.rb
module OauthsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= display_meta_tags(default_meta_tags) %>
  </head>

  <body>
    <header class = "mt-2">
      <div class="title_logo d-inline bg-white text-dark">
        <%= link_to "/" ,class: "btn btn-default" do %>
          <div class="title">お気に入りが見つかる<br>日用品管理アプリ</div>
        <% end %>
      </div>
      <% if logged_in? %>
        <div class="user_menu d-inline bg-white text-dark">
          <%= current_user.name %>
          <%= link_to '在庫管理画面へ',stocks_path %>
          <%= link_to 'ログアウト',logout_path, data: { turbo_method: :delete }  %>
        </div>
      <% end %>
    </header>
    <!-- main class="container mx-auto mt-28 px-5 flex" -->
      <%= yield %>
    <!-- /main-->
  </body>
</html>

app/views/shared/_index_button.html.erb
<div class="buttons">
    <div class="button_container d-flex">
        <%= link_to stocks_path, class: "index_button #{"active" if current_page?(stocks_path)}" do%>
            <div class="p-3 mr-2">現在のストック数</div>
        <% end %>
        <%= link_to soon_path, class: "index_button  #{"active" if current_page?(soon_path)}" do%>
            <div class="p-3 mr-2">そろそろ買い時かも！</div>
        <% end %>
        <%= link_to articles_path, class: "index_button #{"active" if current_page?(articles_path)}" do%>
            <div class="p-3 mr-2">投稿をチェック！</div>
        <% end %>
    </div>
</div>

app/views/shared/_topics.html.erb
<div class="topics ml-3">
    <div class="phone_display">
        <h5 class="text-center">新着記事</h5>
        <div class="article_container_phone">
            <% @phone_articles.each do |art| %>
                <%= link_to article_path(art) do%>
                    <div class="article_phone">
                        <p class="mt-1">
                            カテゴリー：
                            <% if art.categories.first %>
                                <%= art.categories.first.name %>
                            <% else %>
                                カテゴリーがありません
                            <% end %>
                        </p>
                        <p>キーワード：　<%= art.keyword %></p>
                        <p class="article_text_phone mt-3 ml-3"><%=safe_join(art.body.split("\n"),tag(:br)) %></p>
                    </div>
                <% end %>
            <% end %>
        </div>
    </div>
</div>